### PR TITLE
Add tax component to PriceBand, SendMethod and Discounts

### PR DESCRIPTION
**Pull request by charklewis**

### CODE REVIEW

**Review by cakemanny — CHANGES_REQUESTED** [review]
Heya, looking on the right path!
I can see that the behave tests are failing when running them locally, but not related to your changes. @shann9955  has included a fix for that in #107. 

Also see #107 for how Shannon has approached deciding when to include the tax :)

**Comment by cakemanny** [comment]
Hey @joegrimeringresso  and @shann9955 , I've added you as reviewers as I think you're more familiar with the tax implementation that I am. Maybe you want to pass an eye over this.

**Comment by charklewis** [comment]
@shann9955 it looks like your PR is a little more fully featured than mine. Is it worth while me taking my changes across to your PR?

**Comment by shann9955** [comment]
@charklewis I've merged your changes into my PR

**Pull request closed without merging**
