### PR TITLE
Linting - add isort

### PR DESCRIPTION
**Pull request by adamchainz**
isort does do two things here:

1. Ensures imports are in alphabetical order
2. Ensures the __future__ lines are at the top of every file

I also fixed tox.ini to do the linting and docs under python 2.7; before it would use whichever python tox was installed with, which might not be 2.7 !

N.B. this builds on top of #16 so probably won't merge nicely. I'll rebase on top of master after #16 is merged.

### CODE REVIEW

**Comment by nicwest** [comment]
I'm going to check that #16 doesn't break anything on our end then merge. Cheers!

**Comment by nicwest** [comment]
I've merged #16, and this LGTM, if you want to rebase I can merge

**Comment by adamchainz** [comment]
Rebased!

**Comment by nicwest** [comment]
cheers! @tolomea @adamchainz I'm going to rebase these into my woefully out of date python 3 branch and see where it lands.

**Pull request merged**
