### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by tolomea**
I've rebased the existing python3-support branch onto master and fixed the couple of test failures.
The only anomaly currently is that the cassettes aren't being used when testing under Python3.4, I'm looking into that but it doesn't seem like a blocking problem.

### CODE REVIEW

**Comment by tolomea** [comment]
I was wrong about the cassettes, they are being used and work fine.
My actual issue was that if you don't have an appropriate lib python dev installed then coverage falls back to it's Python based tracer which makes the code run literally 10x slower.

**Comment by adamchainz** [comment]
Looks like Travis always installs it

**Comment by nicwest** [comment]
interesting, is this a coverage or cassettes issue?

**Comment by tolomea** [comment]
It's entirely about coverage, the cassettes aren't involved at all.
I incorrectly assumed that since the py34 tests were taking 10x as long as the py27 ones on my machine they must be skipping the cassettes and doing the actual requests.
However investigation revealed that they were actually using the cassettes and it's just that the python based coverage tracer is incredibly slow.

**Comment by nicwest** [comment]
fair enough, worth adding to the readme then. otherwise LGTM

**Comment by tolomea** [comment]
what does this need before it can be merged?

**Comment by nicwest** [comment]
nothing, looks good to me. I will add the note to readme and merge.

**Comment by adamchainz** [comment]
🌈 🐇 🌴 🌞

**Comment by nicwest** [comment]
Cheers for all the work you guys have done on this!

**Comment by adamchainz** [comment]
🐍 🐍 🐍

**Comment by tolomea** [comment]
No problem Nic, in truth it's as much for ourselves as anything, this is
our second last dependency that isn't Py3 compatible, the other one being
our Salesforce library :)

**Pull request merged**
