### PR TITLE
Add modernize linter

### PR DESCRIPTION
**Pull request by adamchainz**
'modernize' is a layer on top of 2to3 for producing Python 2 + 3 compatible code via `six`.

Read more at https://python-modernize.readthedocs.org/en/latest/

This runs it during linting and automatically applies the differences - it's not ideal since it won't fail the tests if something needs changing, but it's not easy to do that without a wrapper script.

### CODE REVIEW

**Comment by nicwest** [comment]
Hey @adamchainz, I think I'm a bit confused about this, I get that modernizer is not a linter, more of an auto refactoring tool, but why does it need to write changes? I seems like this could do unexpected things to peoples code.

**Comment by adamchainz** [comment]
I can add a runtests script to make it fail as a linter if that's better, I use something similar on my projects like : https://github.com/adamchainz/pytest-super-check/blob/master/runtests.py#L41

**Comment by nicwest** [comment]
I don't think we should be failing CI based on this. I would prefer that we had good enough cover so that the tests themselves would fail the CI if we had python2-3 issues.

I have no problem including it as information, but I don't like that this would add a side effect to tox.

**Comment by adamchainz** [comment]
This is the approach we're taking internally to Python 2/3. Personally I think you can't have too many tools linting and trying to predict bugs.

`unicode` versus `str` bugs and `itervalues` versus `values`, etc., are particularly hard to detect with just unit tests, especially since the tests themselves run on the same interpreter as the code and might get things 'wrong' in the same way as the code. Using `six` is a great way to ensure compatibility.

**Comment by nicwest** [comment]
I think you probably can, I'm already having issues with isort but that is beside the point.

My hesitation over this PR is why python-modernizer needs to write the changes it detects?

**Comment by adamchainz** [comment]
If I rewrite it to use a wrapper script, we'll just fail the lint if it detects changes rather than auto-apply them, like `isort`.

**Comment by nicwest** [comment]
sounds good to me

**Comment by adamchainz** [comment]
Updated.

**Comment by nicwest** [comment]
awesome, thanks adam

**Pull request merged**
